export const categoryIcons = [
  { value: '🍔', label: '🍔 Alimentación' },
  { value: '🚗', label: '🚗 Transporte' },
  { value: '🎬', label: '🎬 Entretenimiento' },
  { value: '💡', label: '💡 Servicios' },
  { value: '📚', label: '📚 Educación' },
  { value: '⚕️', label: '⚕️ Salud' },
  { value: '🏠', label: '🏠 Vivienda' },
  { value: '👕', label: '👕 Ropa' },
  { value: '💼', label: '💼 Trabajo' },
  { value: '🎁', label: '🎁 Regalos' },
  { value: '💰', label: '💰 Otros' },
  // Additional icons
  { value: '🍲', label: '🍲 Comida' },
  { value: '🍕', label: '🍕 Pizza' },
  { value: '☕', label: '☕ Café' },
  { value: '🧾', label: '🧾 Facturas' },
  { value: '🎭', label: '🎭 Teatro' },
  { value: '🎮', label: '🎮 Videojuegos' },
  { value: '🎨', label: '🎨 Arte' },
  { value: '📱', label: '📱 Teléfono' },
  { value: '💻', label: '💻 Informática' },
  { value: '👶', label: '👶 Bebés' },
  { value: '🐶', label: '🐶 Mascotas' },
  { value: '🏋️', label: '🏋️ Gimnasio' },
  { value: '🎯', label: '🎯 Metas' },
  { value: '✈️', label: '✈️ Viajes' },
  { value: '🏦', label: '🏦 Banco' },
  { value: '💉', label: '💉 Medicamentos' },
  { value: '🚌', label: '🚌 Autobús' },
  { value: '🚇', label: '🚇 Metro' },
  { value: '🚲', label: '🚲 Bicicleta' },
  { value: '💝', label: '💝 Donaciones' },
  { value: '🎧', label: '🎧 Música' },
  { value: '📺', label: '📺 Streaming' },
  { value: '📷', label: '📷 Fotografía' },
  { value: '💇', label: '💇 Peluquería' },
  { value: '👔', label: '👔 Traje' },
  { value: '👟', label: '👟 Calzado' },
  { value: '💍', label: '💍 Joyería' },
  { value: '🏨', label: '🏨 Hotel' },
  { value: '🍷', label: '🍷 Vino' },
  { value: '🍻', label: '🍻 Cerveza' },
];
